### ISSUE TITLE
What is the license of this OggSpeex project?

### ISSUE THREAD

**Issue by chenweiyj** [jcccn/OggSpeex#1]
Hi, @jcccn 

I recently is dealing with the speex encoding/decoding in iOS; and I have found this OggSpeex in github which might solve my problem. However, I cannot find an open source license along with it. So I wonder what the license of this project is and if it is safe to merge to my project. 

Thank you.

**Comment by jcccn** [comment]
尽管用好了。
我封装的代码没有版权的。其中涉及到的ogg使用的是开源的Xiph.Org组织的，也不会有什么问题。
我这个项目，因为没有时间去维护，所以会在使用中遇到一些bug。以及以前经验的问题，导致代码结构写得不好，根据需要改进吧。
不过，相比speex（http://speex.org/），新项目Opus（http://www.opus-codec.org/）是一个更优秀的选择。
谢谢
